name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to amazon ECR
      env:
        ECR_REGISTRY: $${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: srujan-ecr-repo
        IMAGE_TAG: 2048
      run: |
        docker build -t 2048-game .
        docker tag 2048-game srujan-ecr-repo:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:2048-game